// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9sOMuWXvHlnP-9tDIIW0CrStwUYSSeaI',
    appId: '1:175476558296:web:4448e42c79e5a213d18aad',
    messagingSenderId: '175476558296',
    projectId: 'musicapp-376b2',
    authDomain: 'musicapp-376b2.firebaseapp.com',
    storageBucket: 'musicapp-376b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_mRHcQxnypYiay6MLWEy70PpG2VzA_w',
    appId: '1:175476558296:android:ff9ec4f7c68e6e2ad18aad',
    messagingSenderId: '175476558296',
    projectId: 'musicapp-376b2',
    storageBucket: 'musicapp-376b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi8XJuW7Bz6Unm58JTEuJiJ6ehqWaRhJY',
    appId: '1:175476558296:ios:cf7d4cd1749de9a8d18aad',
    messagingSenderId: '175476558296',
    projectId: 'musicapp-376b2',
    storageBucket: 'musicapp-376b2.firebasestorage.app',
    iosBundleId: 'com.example.music',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi8XJuW7Bz6Unm58JTEuJiJ6ehqWaRhJY',
    appId: '1:175476558296:ios:cf7d4cd1749de9a8d18aad',
    messagingSenderId: '175476558296',
    projectId: 'musicapp-376b2',
    storageBucket: 'musicapp-376b2.firebasestorage.app',
    iosBundleId: 'com.example.music',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9sOMuWXvHlnP-9tDIIW0CrStwUYSSeaI',
    appId: '1:175476558296:web:485f9cf8c80b5af3d18aad',
    messagingSenderId: '175476558296',
    projectId: 'musicapp-376b2',
    authDomain: 'musicapp-376b2.firebaseapp.com',
    storageBucket: 'musicapp-376b2.firebasestorage.app',
  );
}
